"""Offline terminal script — run YOLO + angle extraction on an expert video.

NEVER called by the app. Run manually from the terminal:

  cd "AugMentor 2.0/backend"
  python -m app.scripts.angle.process_expert_angles \
      --video_path path/to/expert.mp4 \
      --expert_name straight_line_v1

Outputs saved to storage/outputs/angles/expert/<expert_name>/:
  angles.json            — per-frame angle data (used by learner DTW pipeline)
  yolo_detections.json   — raw YOLO detection log
  annotated_expert.mp4   — annotated video with YOLO bbox + angle line drawn
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import cv2
import numpy as np

# Allow running as a script: add backend/ to sys.path so app.* imports work.
_BACKEND_ROOT = Path(__file__).resolve().parents[3]
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))

from app.core.config import settings  # noqa: E402
from app.services.angle.detector import (  # noqa: E402
    ANGLE_JUMP_LIMIT_DEGREES,
    LOW_CONFIDENCE_ANGLE_THRESHOLD,
    YOLO_CONFIDENCE,
    YOLO_MODEL_PATH,
    angle_delta_degrees,
    angle_from_points,
    build_video_frames_payload,
    detect_scissors,
    estimate_blade_angle_from_crop,
    extend_angle_line,
    get_yolo_model,
    normalize_angle_180,
    pick_best_scissors,
    smooth_angle,
)
from app.services.angle.schemas import (  # noqa: E402
    ANGLES_FILENAME,
    YOLO_DETECTIONS_FILENAME,
)
from ultralytics import YOLO  # noqa: E402

ANNOTATED_VIDEO_FILENAME = "annotated_expert.mp4"


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run YOLO + angle extraction on an expert video and save outputs offline."
    )
    parser.add_argument(
        "--video_path",
        required=True,
        help="Path to the expert video file.",
    )
    parser.add_argument(
        "--expert_name",
        required=True,
        help='Expert identifier used as the output folder name, e.g. "straight_line_v1".',
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=1,
        help="Frame stride (default: 1 — process every frame).",
    )
    parser.add_argument(
        "--conf",
        type=float,
        default=YOLO_CONFIDENCE,
        help=f"YOLO confidence threshold (default: {YOLO_CONFIDENCE}).",
    )
    parser.add_argument(
        "--device",
        default=None,
        help='Ultralytics device, e.g. "0" for GPU or "cpu".',
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing output files if present.",
    )
    parser.add_argument(
        "--no-video",
        dest="no_video",
        action="store_true",
        help="Skip annotated video output (JSON only).",
    )
    return parser


def _transcode(input_avi: Path, output_mp4: Path, fps: float) -> None:
    """Transcode MJPEG AVI to H.264 MP4 via imageio-ffmpeg."""
    import imageio_ffmpeg

    ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
    if output_mp4.exists():
        output_mp4.unlink()

    cmd = [
        ffmpeg, "-y", "-hide_banner", "-loglevel", "error",
        "-i", str(input_avi),
        "-an", "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-preset", "veryfast", "-crf", "23",
        "-movflags", "+faststart",
        "-r", str(fps),
        str(output_mp4),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"FFmpeg failed (exit {result.returncode}): {result.stderr[:500]}"
        )


def _draw_frame(
    frame: np.ndarray,
    *,
    bbox: list[float] | None,
    confidence: float,
    status: str,
    line_angle: float | None,
    center_x: float,
    center_y: float,
    width: int,
    height: int,
) -> None:
    """Draw YOLO bbox (red) and angle line (green) onto the frame.

    No angle value text is drawn here — text overlays appear only on
    learner_comparison_output.mp4 generated by preview.py.
    """
    if bbox is None:
        return

    x1, y1, x2, y2 = map(int, bbox)

    # Red bounding box
    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 255), 2)

    # Confidence + status label on the bbox
    label = f"scissors {confidence:.2f} [{status}]"
    cv2.putText(
        frame, label, (x1, max(20, y1 - 10)),
        cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 0, 255), 2, cv2.LINE_AA,
    )

    if line_angle is not None:
        # Green angle line through center — no angle number text
        start, end = extend_angle_line(line_angle, center_x, center_y, width, height)
        cv2.line(frame, start, end, (0, 255, 0), 4)


def main() -> None:
    args = build_arg_parser().parse_args()

    video_path = Path(args.video_path).expanduser().resolve()
    if not video_path.is_file():
        print(f"ERROR: video not found: {video_path}", file=sys.stderr)
        sys.exit(1)

    expert_name = args.expert_name.strip()
    if not expert_name:
        print("ERROR: --expert_name must not be empty", file=sys.stderr)
        sys.exit(1)

    frame_stride = max(1, int(args.stride))
    out_dir: Path = settings.ANGLES_OUTPUT_ROOT / "expert" / expert_name
    out_dir.mkdir(parents=True, exist_ok=True)

    angles_path = out_dir / ANGLES_FILENAME
    detections_path = out_dir / YOLO_DETECTIONS_FILENAME
    video_out_path = out_dir / ANNOTATED_VIDEO_FILENAME

    if angles_path.is_file() and not args.overwrite:
        print(
            f"Output already exists: {angles_path}\n"
            "Pass --overwrite to replace it."
        )
        sys.exit(0)

    # ── Load model ────────────────────────────────────────────────────────────
    print(f"YOLO model:  {YOLO_MODEL_PATH}")
    if args.device is not None:
        model = YOLO(str(YOLO_MODEL_PATH))
        model.to(args.device)
    else:
        model = get_yolo_model()

    print(f"Expert:      {expert_name}")
    print(f"Video:       {video_path}")
    print(f"Output dir:  {out_dir}")
    print(f"Stride:      {frame_stride}")
    print(f"Confidence:  {args.conf}")
    print(f"Write video: {not args.no_video}")
    print()

    # ── Open video ────────────────────────────────────────────────────────────
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        print(f"ERROR: Could not open video: {video_path}", file=sys.stderr)
        sys.exit(1)

    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    if width <= 0 or height <= 0:
        cap.release()
        print("ERROR: Invalid video dimensions", file=sys.stderr)
        sys.exit(1)

    # ── Set up video writer (MJPEG → AVI, then transcode to H.264 MP4) ───────
    writer = None
    tmp_avi_path = out_dir / "annotated_expert.tmp.avi"
    tmp_mp4_path = out_dir / "annotated_expert.tmp.mp4"

    if not args.no_video:
        writer = cv2.VideoWriter(
            str(tmp_avi_path),
            cv2.VideoWriter_fourcc(*"MJPG"),
            float(fps),
            (width, height),
        )
        if not writer.isOpened():
            cap.release()
            print("ERROR: Could not create video writer", file=sys.stderr)
            sys.exit(1)

    # ── Main processing loop ──────────────────────────────────────────────────
    frames: list[dict] = []
    raw_detection_frames: list[dict] = []
    frame_index = 0
    detections_count = 0
    last_bbox: list[float] | None = None
    last_confidence = 0.0
    previous_angle: float | None = None

    try:
        while True:
            ok, frame = cap.read()
            if not ok:
                break

            status = "skipped"
            bbox = None
            confidence = 0.0
            line_center = None
            line_angle = None
            line_start = None
            line_end = None
            line_source = "none"
            fallback_used = False
            valid_line = False
            raw_detections: list[dict] = []

            if frame_index % frame_stride == 0:
                predictions = detect_scissors(frame, model)
                picked, _ = pick_best_scissors(predictions, width, height)
                raw_detections = predictions

                if picked is not None:
                    bbox = [float(v) for v in picked["bbox"]]
                    confidence = float(picked.get("confidence", 0.0))
                    last_bbox = bbox
                    last_confidence = confidence
                    detections_count += 1
                    status = "detected"
                else:
                    status = "no_detection"
            else:
                if last_bbox is not None:
                    bbox = last_bbox
                    confidence = last_confidence
                    status = "reused"

            raw_detection_frames.append(
                {
                    "frame_index": frame_index,
                    "status": status,
                    "detections": raw_detections,
                }
            )

            center_x = 0.0
            center_y = 0.0

            if bbox is not None:
                x1, y1, x2, y2 = map(int, bbox)
                center_x = (x1 + x2) / 2.0
                center_y = (y1 + y2) / 2.0
                line_center = [round(center_x, 3), round(center_y, 3)]

                bbox_angle = angle_from_points((x1, y1), (x2, y2))
                blade_angle = estimate_blade_angle_from_crop(frame, (x1, y1, x2, y2))

                if previous_angle is None:
                    if blade_angle is not None:
                        angle_to_draw = blade_angle
                        line_source = "fitline"
                    else:
                        angle_to_draw = bbox_angle
                        line_source = "bbox_diagonal"
                        fallback_used = True
                elif blade_angle is None or confidence < LOW_CONFIDENCE_ANGLE_THRESHOLD:
                    angle_to_draw = previous_angle
                    line_source = "previous_frame"
                    fallback_used = True
                else:
                    jump = abs(angle_delta_degrees(previous_angle, blade_angle))
                    if jump > ANGLE_JUMP_LIMIT_DEGREES:
                        angle_to_draw = previous_angle
                        line_source = "previous_frame"
                        fallback_used = True
                    else:
                        angle_to_draw = smooth_angle(previous_angle, blade_angle)
                        line_source = "fitline"

                start, end = extend_angle_line(angle_to_draw, center_x, center_y, width, height)
                line_start = [int(start[0]), int(start[1])]
                line_end = [int(end[0]), int(end[1])]
                previous_angle = angle_to_draw
                line_angle = round(float(angle_to_draw), 6)
                valid_line = True

            # Draw annotations onto frame
            if writer is not None:
                _draw_frame(
                    frame,
                    bbox=bbox,
                    confidence=confidence,
                    status=status,
                    line_angle=line_angle,
                    center_x=center_x,
                    center_y=center_y,
                    width=width,
                    height=height,
                )
                writer.write(frame)

            frames.append(
                {
                    "frame_index": frame_index,
                    "bbox": bbox,
                    "confidence": round(confidence, 6),
                    "line_center": line_center,
                    "line_angle": line_angle,
                    "line_start": line_start,
                    "line_end": line_end,
                    "line_source": line_source,
                    "fallback_used": fallback_used,
                    "valid_line": valid_line,
                    "status": status,
                }
            )

            frame_index += 1

            if frame_index % 100 == 0:
                print(f"  Processed {frame_index} frames, {detections_count} detections...", flush=True)

    finally:
        cap.release()
        if writer is not None:
            writer.release()

    if frame_index == 0:
        print("ERROR: No frames processed", file=sys.stderr)
        sys.exit(1)

    # ── Transcode AVI → H.264 MP4 ─────────────────────────────────────────────
    if not args.no_video and tmp_avi_path.exists():
        print("Transcoding annotated video to H.264 MP4...")
        try:
            _transcode(tmp_avi_path, tmp_mp4_path, float(fps))
            tmp_avi_path.unlink(missing_ok=True)
            if video_out_path.exists():
                video_out_path.unlink()
            tmp_mp4_path.replace(video_out_path)
            print(f"Saved {ANNOTATED_VIDEO_FILENAME} → {video_out_path}")
        except Exception as exc:
            tmp_avi_path.unlink(missing_ok=True)
            tmp_mp4_path.unlink(missing_ok=True)
            print(f"WARNING: Video transcode failed: {exc}", file=sys.stderr)

    # ── Save angles.json ──────────────────────────────────────────────────────
    angles_payload = build_video_frames_payload(
        video_type="expert",
        video_path=str(video_path),
        total_frames=frame_index,
        fps=float(fps),
        frames=frames,
    )
    angles_path.write_text(json.dumps(angles_payload, indent=2), encoding="utf-8")
    print(f"Saved {ANGLES_FILENAME} → {angles_path}")

    # ── Save yolo_detections.json ─────────────────────────────────────────────
    detections_payload = {
        "video_path": str(video_path),
        "total_frames": frame_index,
        "fps": round(float(fps), 6),
        "frame_stride": frame_stride,
        "confidence_threshold": args.conf,
        "frames": raw_detection_frames,
    }
    detections_path.write_text(json.dumps(detections_payload, indent=2), encoding="utf-8")
    print(f"Saved {YOLO_DETECTIONS_FILENAME} → {detections_path}")

    valid_count = sum(1 for f in frames if f["valid_line"])
    print()
    print(f"Done. {frame_index} frames | {detections_count} detections | {valid_count} valid angles")


if __name__ == "__main__":
    main()
