"""SAM 2 pipeline services (tracking + run orchestration)."""

from app.services.sam2.pipeline_service import (
    SAM2ContractArtifacts,
    SAM2PipelineError,
    build_sam2_raw_document,
    build_sam2_summary_document,
    copy_contract_artifacts_to,
    get_runs_root as get_pipeline_runs_root,
    load_sam2_contract_artifacts,
    process_learner_sam2,
    resolve_run_dir as resolve_pipeline_run_dir,
    run_sam2_from_mediapipe_prompt,
)
from app.services.sam2.sam2_service import (
    SAM2AssetsMissingError,
    SAM2DependencyError,
    SAM2Error,
    SAM2GPUOutOfMemoryError,
    SAM2InitError,
    SAM2RunArtifacts,
    build_init_prompt_from_mediapipe,
    build_manual_init_prompt,
    build_manual_point_prompt,
    build_sam2_auto_prompt,
    collect_first_n_valid_prompt_frames,
    find_first_valid_sam2_prompt,
    get_runs_root,
    get_sam2_asset_paths,
    get_video_predictor,
    load_mediapipe_features,
    load_run_artifacts,
    reset_video_predictor_cache,
    resolve_device,
    resolve_device_info,
    resolve_run_dir,
    resolve_video_path,
    run_sam2_pipeline,
    validate_sam2_assets,
)
from app.services.sam2.tip_tracking_service import (
    SAM2TipTrackingArtifacts,
    SAM2TipTrackingError,
    track_scissor_tip_in_sam_roi,
)

__all__ = [
    "SAM2ContractArtifacts",
    "SAM2AssetsMissingError",
    "SAM2DependencyError",
    "SAM2Error",
    "SAM2GPUOutOfMemoryError",
    "SAM2InitError",
    "SAM2PipelineError",
    "SAM2RunArtifacts",
    "build_init_prompt_from_mediapipe",
    "build_manual_init_prompt",
    "build_manual_point_prompt",
    "build_sam2_auto_prompt",
    "build_sam2_raw_document",
    "build_sam2_summary_document",
    "collect_first_n_valid_prompt_frames",
    "copy_contract_artifacts_to",
    "find_first_valid_sam2_prompt",
    "get_pipeline_runs_root",
    "get_runs_root",
    "get_sam2_asset_paths",
    "get_video_predictor",
    "load_mediapipe_features",
    "load_run_artifacts",
    "load_sam2_contract_artifacts",
    "process_learner_sam2",
    "reset_video_predictor_cache",
    "resolve_device",
    "resolve_device_info",
    "resolve_pipeline_run_dir",
    "resolve_run_dir",
    "resolve_video_path",
    "run_sam2_from_mediapipe_prompt",
    "run_sam2_pipeline",
    "SAM2TipTrackingArtifacts",
    "SAM2TipTrackingError",
    "track_scissor_tip_in_sam_roi",
    "validate_sam2_assets",
]
